// Product image catalogue — plain data (no imports) so the image sync script
// can load it directly. Each row: [key, image, label, match words].
//   image: an emoji rendered from bundled Twemoji SVGs, or "x:<name>" for a
//          custom drawing in public/product-images/x-<name>.svg.
//   match words: comma-separated names, local names and brands (lowercase).
// Keys are stored on products, so never rename an existing key.

export type ImageGroupId =
  | "fruit" | "vegetables" | "staples" | "bakery" | "dairy" | "meat" | "snacks"
  | "drinks" | "alcohol" | "household" | "personal" | "baby" | "health"
  | "stationery" | "electronics" | "kitchen" | "hardware" | "clothing"
  | "farm" | "toys" | "other";

export type CatalogRow = [key: string, image: string, label: string, words: string];

export interface ImageGroupDef {
  id: ImageGroupId;
  label: string;
  fallback: string; // image key used when only the category is known
  aliases: string; // category words that map to this group
}

export const IMAGE_GROUPS: ImageGroupDef[] = [
  { id: "fruit", label: "Fruit", fallback: "apple", aliases: "fruit, fruits" },
  { id: "vegetables", label: "Vegetables", fallback: "leafy-greens", aliases: "vegetable, vegetables, veg, greens, produce, fresh produce" },
  { id: "staples", label: "Food staples", fallback: "rice", aliases: "grocery, groceries, food, foods, provisions, cereals, dry foods, foodstuff, foodstuffs, staples" },
  { id: "bakery", label: "Bakery", fallback: "bread", aliases: "bakery, baked, bread, pastries, confectionery bakery" },
  { id: "dairy", label: "Dairy & eggs", fallback: "milk", aliases: "dairy, milk products, eggs" },
  { id: "meat", label: "Meat & fish", fallback: "meat", aliases: "meat, butchery, butcher, fish, poultry meat, seafood" },
  { id: "snacks", label: "Snacks & sweets", fallback: "cookie", aliases: "snack, snacks, sweets, confectionery, candy, fast food, takeaway" },
  { id: "drinks", label: "Drinks", fallback: "soda", aliases: "drink, drinks, beverage, beverages, soft drinks, juices" },
  { id: "alcohol", label: "Alcohol", fallback: "beer", aliases: "alcohol, liquor, bar, beers, wines, spirits, wines and spirits" },
  { id: "household", label: "Household", fallback: "detergent", aliases: "household, cleaning, home, home care, detergents, domestic" },
  { id: "personal", label: "Personal care", fallback: "lotion", aliases: "personal care, toiletries, cosmetics, beauty, salon, hygiene" },
  { id: "baby", label: "Baby", fallback: "diapers", aliases: "baby, babies, infant, kids care" },
  { id: "health", label: "Health", fallback: "pills", aliases: "health, pharmacy, drug shop, drugs, medicine, medical, clinic" },
  { id: "stationery", label: "Stationery", fallback: "notebook", aliases: "stationery, stationary, school, school supplies, office, books" },
  { id: "electronics", label: "Electronics", fallback: "phone", aliases: "electronics, electronic, phones, accessories, phone accessories, electrical, computers, gadgets" },
  { id: "kitchen", label: "Kitchen & utensils", fallback: "plate", aliases: "kitchen, utensils, kitchenware, cookware, crockery, cutlery" },
  { id: "hardware", label: "Hardware & fuel", fallback: "toolbox", aliases: "hardware, tools, building, construction, fuel, auto, spare parts, spares, motor" },
  { id: "clothing", label: "Clothing & fashion", fallback: "tshirt", aliases: "clothing, clothes, fashion, apparel, shoes, footwear, boutique, jewellery" },
  { id: "farm", label: "Farm & pets", fallback: "seedling", aliases: "farm, agro, agriculture, agricultural, farming, animal feeds, feeds, livestock, pets, vet" },
  { id: "toys", label: "Toys, sports & gifts", fallback: "teddy", aliases: "toys, toy, sports, sport, games, gifts, party" },
  { id: "other", label: "Other", fallback: "shopping-bags", aliases: "other, others, general, misc, miscellaneous" },
];

export const CATALOG_ROWS: Record<ImageGroupId, CatalogRow[]> = {
  fruit: [
    ["apple", "🍎", "Apple", "apple, red apple"],
    ["green-apple", "🍏", "Green apple", "green apple"],
    ["pear", "🍐", "Pear", "pear"],
    ["orange", "🍊", "Orange", "orange, tangerine, mandarin, clementine, oranges"],
    ["lemon", "🍋", "Lemon & lime", "lemon, lime, ndimu"],
    ["banana", "🍌", "Banana", "banana, bogoya, sweet banana, ripe banana, ndizi, ndiizi"],
    ["matooke", "🍌", "Matooke", "matooke, plantain, gonja, cooking banana, green banana, ebitooke, bunch"],
    ["watermelon", "🍉", "Watermelon", "watermelon, water melon"],
    ["grapes", "🍇", "Grapes", "grapes, grape, raisins"],
    ["strawberry", "🍓", "Strawberry", "strawberry, strawberries"],
    ["blueberries", "🫐", "Berries", "blueberry, blueberries, berries, gooseberry, entuutu"],
    ["melon", "🍈", "Melon & jackfruit", "melon, cantaloupe, jackfruit, fenne, passion, passion fruit, passions"],
    ["cherries", "🍒", "Cherries", "cherry, cherries"],
    ["peach", "🍑", "Peach & plum", "peach, apricot, plum, nectarine"],
    ["mango", "🥭", "Mango", "mango, embale, emiyembe, muyembe"],
    ["pineapple", "🍍", "Pineapple", "pineapple, nanasi, enanansi"],
    ["coconut", "🥥", "Coconut", "coconut, coconuts, nazi"],
    ["kiwi-fruit", "🥝", "Kiwi fruit", "kiwi fruit"],
    ["avocado", "🥑", "Avocado", "avocado, ovacado, avacado, ovakedo"],
    ["olive", "🫒", "Olives", "olive, olives"],
  ],
  vegetables: [
    ["tomato", "🍅", "Tomato", "tomato, nyanya, tomatoes"],
    ["eggplant", "🍆", "Eggplant", "eggplant, aubergine, brinjal, biringanya, entula, garden egg"],
    ["potato", "🥔", "Irish potato", "potato, irish potato, irish, irish potatoes, lumonde irish"],
    ["carrot", "🥕", "Carrot", "carrot, carrots"],
    ["corn", "🌽", "Maize cob", "maize, corn, maize cob, roasted maize, kasooli, green maize, sweet corn"],
    ["chili", "🌶️", "Chilli", "chili, chilli, hot pepper, pilipili, kamulali, akabanga, chilli sauce"],
    ["bell-pepper", "🫑", "Green pepper", "green pepper, bell pepper, capsicum, sweet pepper, pepper"],
    ["cucumber", "🥒", "Cucumber", "cucumber, courgette, zucchini"],
    ["leafy-greens", "🥬", "Leafy greens", "cabbage, sukuma, sukuma wiki, dodo, nakati, spinach, lettuce, greens, kale, bbuga, amaranth, eshwiga, ebbugga, borro, malakwang"],
    ["broccoli", "🥦", "Broccoli", "broccoli, cauliflower"],
    ["garlic", "🧄", "Garlic", "garlic, kitungu saumu"],
    ["onion", "🧅", "Onion", "onion, red onion, spring onion, leek, bulb onion, obutungulu"],
    ["mushroom", "🍄", "Mushroom", "mushroom, mushrooms, obutiko, butiko"],
    ["sweet-potato", "🍠", "Sweet potato & cassava", "sweet potato, lumonde, cassava, muwogo, yam, arrowroot, ndaggu, balugu, taro, sweet potatoes"],
    ["ginger", "🫚", "Ginger", "ginger, tangawizi"],
    ["peas", "🫛", "Peas", "peas, green peas, pea, french beans, green beans, pigeon peas"],
    ["beans", "🫘", "Beans", "beans, bean, kidney beans, dry beans, ebijanjaalo, lentils, ndengu, soya, soy beans, soybeans, cowpeas, nambale, yellow beans"],
    ["peanuts", "🥜", "Groundnuts", "groundnuts, g nuts, gnuts, peanuts, peanut, ebinyebwa, binyebwa, nuts, roasted groundnuts"],
    ["seeds-nuts", "🌰", "Nuts & seeds", "chestnut, cashew, cashews, almonds, macadamia, sesame, simsim, sim sim, pumpkin seeds"],
    ["herbs", "🌿", "Herbs", "herbs, dhania, coriander, parsley, mint, rosemary, lemongrass, basil"],
    ["pumpkin", "🎃", "Pumpkin", "pumpkin, squash, ensujju, butternut"],
  ],
  staples: [
    ["rice", "🍚", "Rice", "rice, pishori, super rice, basmati, kaiso, brown rice, rice grain"],
    ["flour", "x:flour", "Flour", "flour, maize flour, posho, kawunga, wheat flour, baking flour, atta, millet flour, cassava flour, sorghum flour, unga, obuwunga"],
    ["sugar", "x:sugar", "Sugar", "sugar, brown sugar, white sugar, kakira, kinyara, lugazi, scoul, sukaali"],
    ["salt", "🧂", "Salt", "salt, iodised salt, iodized salt, kensalt, table salt, rock salt, munnyo"],
    ["spices", "🧂", "Spices & seasoning", "spices, spice, curry, curry powder, masala, pilau masala, seasoning, royco, stock cubes, maggi, black pepper, tea masala, mchuzi mix, turmeric"],
    ["wheat", "🌾", "Grains", "wheat, millet, sorghum, barley, bulo, grain, grains, oats grain"],
    ["noodles", "🍜", "Noodles", "noodles, indomie, instant noodles, ramen, noodle"],
    ["pasta", "🍝", "Pasta", "spaghetti, pasta, macaroni"],
    ["cereal", "🥣", "Cereal & porridge", "cereal, cornflakes, corn flakes, oats, porridge, weetabix, muesli, uji, obuugi, oat meal, oatmeal"],
    ["canned", "🥫", "Tinned food", "tinned, canned, baked beans, sardines, tuna, tomato paste, corned beef, tin, tinned fish, can food"],
    ["honey", "🍯", "Honey", "honey, obubaki"],
    ["jar", "🫙", "Spreads & jars", "jam, jar, peanut butter, mayonnaise, pickle, marmalade, spread, groundnut paste, ebinyebwa paste"],
    ["cooking-oil", "x:cooking-oil", "Cooking oil", "cooking oil, oil, vegetable oil, sunflower oil, palm oil, olive oil, mukwano oil, fortune, golden fry, sunseed, elianto, tamu oil, cooking fat, kimbo, fat"],
    ["tea", "🍵", "Tea", "tea, tea leaves, chai, green tea, tea bags, majani, kericho, african pride, chai leaves"],
    ["coffee", "☕", "Coffee & cocoa", "coffee, nescafe, instant coffee, africafe, kahawa, milo, cocoa, drinking chocolate, ovaltine, touchdown"],
    ["egg", "🥚", "Eggs", "egg, eggs, tray of eggs, amagi, tray eggs"],
  ],
  bakery: [
    ["bread", "🍞", "Bread", "bread, loaf, sliced bread, toast, brown bread, white bread, supa loaf, hot loaf, family loaf, mugaati, bread loaf"],
    ["baguette", "🥖", "Baguette", "baguette, french bread, long bread, french loaf"],
    ["croissant", "🥐", "Croissant & pastries", "croissant, pastry, pastries, danish, pastry puff"],
    ["buns", "🥯", "Buns & rolls", "bun, buns, bread roll, rolls, bagel, sweet bun, dinner roll"],
    ["pretzel", "🥨", "Pretzel", "pretzel, pretzels, twist"],
    ["flatbread", "🫓", "Chapati", "chapati, chapatti, naan, flatbread, pita, tortilla, kikomando"],
    ["pancake", "🥞", "Pancakes", "pancake, pancakes, kabalagala, crepe"],
    ["waffle", "🧇", "Waffle", "waffle, waffles"],
    ["doughnut", "🍩", "Doughnut & mandazi", "doughnut, donut, mandazi, maandazi, andazi, half cake, kabooli, donuts"],
    ["cookie", "🍪", "Biscuits", "biscuit, biscuits, cookies, cookie, cream crackers, crackers, digestive, nice biscuits, glucose biscuits, marie, shortbread, rich tea"],
    ["cake", "🍰", "Cake", "cake, cakes, slice of cake, sponge cake, black forest, fruit cake"],
    ["cupcake", "🧁", "Cupcakes", "cupcake, queen cake, muffin, muffins, queencakes, cupcakes"],
    ["birthday-cake", "🎂", "Celebration cake", "birthday cake, wedding cake, celebration cake"],
    ["pie", "🥧", "Pies", "pie, meat pie, tart, chicken pie"],
  ],
  dairy: [
    ["milk", "🥛", "Milk & yoghurt", "milk, fresh milk, lato, fresh dairy, yoghurt, yogurt, mala, sour milk, pakalast, long life milk, uht, milk powder, nido, cowbell, dairy, amata, jesa, bbiri, brookside, lato milk"],
    ["cheese", "🧀", "Cheese", "cheese, cheddar, mozzarella, gouda"],
    ["butter", "🧈", "Butter & margarine", "butter, margarine, blue band, blueband, prestige, ghee, butter spread"],
    ["ice-cream", "🍦", "Ice cream", "ice cream, icecream, soft serve, cone, ice lolly, ice pop"],
    ["custard", "🍮", "Custard & dessert", "custard, pudding, jelly, dessert, creme caramel"],
  ],
  meat: [
    ["meat", "🥩", "Beef & goat meat", "meat, beef, steak, goat meat, mutton, liver, offals, minced meat, mince, nyama, beef steak, ennyama"],
    ["chicken-meat", "🍗", "Chicken", "chicken, chicken wings, drumstick, drumsticks, chicken legs, kuku, broiler meat, whole chicken, chicken breast, gizzards"],
    ["pork", "🥓", "Pork & bacon", "bacon, pork, ham, pork ribs, porkchops, pork chops, embizzi"],
    ["roast-meat", "🍖", "Roast meat", "meat on bone, muchomo, nyama choma, roast meat, ribs, roasted meat, goat ribs"],
    ["sausage", "🌭", "Sausages", "sausage, sausages, hotdog, hot dog, smokie, smokies, frankfurter"],
    ["fish", "🐟", "Fish", "fish, tilapia, ngege, nile perch, mputa, silverfish, mukene, omena, dagaa, smoked fish, dry fish, salted fish, catfish, male, fish fillet, enkejje, fillet"],
    ["prawns", "🍤", "Prawns", "prawns, shrimp, shrimps"],
    ["bones", "🦴", "Soup bones", "soup bones, bones, marrow bones, bone"],
  ],
  snacks: [
    ["samosa", "🥟", "Samosa", "samosa, sambusa, samosas, dumpling, spring roll, sambusa beef"],
    ["sandwich", "🥪", "Sandwich", "sandwich, sandwiches, sub"],
    ["burger", "🍔", "Burger", "burger, hamburger, cheeseburger, burgers"],
    ["fries", "🍟", "Chips & crisps", "chips, fries, french fries, crisps, potato crisps, chipsi, potato chips, pringles"],
    ["pizza", "🍕", "Pizza", "pizza, pizzas"],
    ["wrap", "🌯", "Rolex & wraps", "rolex, wrap, shawarma, burrito, rolled eggs, rolex wrap"],
    ["popcorn", "🍿", "Popcorn", "popcorn, pop corn, bisi"],
    ["chocolate", "🍫", "Chocolate", "chocolate, cadbury, dairy milk, kitkat, snickers, mars, bounty, chocolate bar"],
    ["sweets", "🍬", "Sweets & gum", "sweets, sweet, candy, toffee, mint, mints, chewing gum, gum, big g, orbit, bubble gum, lozenges, pipi, sweeties"],
    ["lollipop", "🍭", "Lollipop", "lollipop, lollipops, lolly"],
    ["curry-plate", "🍛", "Cooked meals", "pilau, pilao, biryani, meal, plate of food, lunch, food plate, katogo, lusaniya"],
    ["soup", "🍲", "Soup & stew", "soup, stew, broth, luwombo, sauce, beef stew, groundnut soup"],
    ["salad", "🥗", "Salad", "salad, coleslaw, kachumbari, vegetable salad"],
    ["skewers", "🍢", "Skewers", "skewers, mshikaki, meat sticks, muchomo sticks, gonja sticks"],
    ["meatballs", "🧆", "Meatballs & falafel", "meatballs, falafel, bean balls"],
    ["kebab", "🥙", "Kebab & pita", "kebab, gyro, pita sandwich, stuffed pita"],
    ["taco", "🌮", "Tacos", "taco, tacos"],
    ["packed-meal", "🍱", "Packed meals", "packed lunch, lunch pack, takeaway meal, food pack, meal box"],
  ],
  drinks: [
    ["water", "x:water-bottle", "Water", "water, mineral water, drinking water, rwenzori, aquafina, dasani, jibu, bottled water, highland water, aqua"],
    ["soda", "🥤", "Soda", "soda, soft drink, coca cola, coke, fanta, sprite, pepsi, mirinda, mountain dew, 7up, novida, stoney, krest, bitter lemon, tonic, soda bottle, minute maid soda"],
    ["juice", "🧃", "Juice", "juice, minute maid, splash, afia, cheers, ribena, mango juice, fruit juice, quencher, sunquick, passion juice, highlands juice"],
    ["energy-drink", "⚡", "Energy drink", "energy drink, rockboom, rock boom, red bull, sting, power play, monster, predator, energy"],
    ["milkshake", "🧋", "Milkshake & smoothie", "milkshake, smoothie, bubble tea, shake"],
    ["ice", "🧊", "Ice", "ice, ice cubes, ice block"],
  ],
  alcohol: [
    ["beer", "🍺", "Beer", "beer, lager, nile special, nile, club, club pilsener, bell lager, bell, tusker, guinness, castle, eagle, senator, pilsner, stout, heineken, smirnoff ice, beers"],
    ["wine", "🍷", "Wine", "wine, red wine, white wine, 4th street, fourth street, sweet wine, altar wine, drostdy hof, wines"],
    ["spirits", "🥃", "Spirits", "waragi, uganda waragi, whisky, whiskey, brandy, vodka, rum, spirits, liqueur, jameson, johnnie walker, bond 7, tot, sachet, kick waragi, coffee spirit"],
    ["gin", "🍸", "Gin & cocktails", "gin, cocktail, martini, gilbeys, gordons"],
    ["champagne", "🍾", "Sparkling wine", "champagne, sparkling wine, prosecco, sparkling"],
    ["local-brew", "🍶", "Local brew", "tonto, malwa, kwete, ajon, local brew, mwenge bigere, obushera, bushera, busaa"],
    ["beer-crate", "🍻", "Beer crates", "crate, beer crate, crate of beer, crates, empties"],
    ["punch", "🍹", "Punch & mocktails", "punch, fruit punch, mocktail, cocktail juice"],
  ],
  household: [
    ["soap", "🧼", "Bar soap", "soap, bar soap, bathing soap, laundry soap, mukwano soap, geisha, protex, lifebuoy, white star, sunlight bar, washing soap, star soap, bar, key soap"],
    ["detergent", "🫧", "Detergent & cleaners", "detergent, washing powder, omo, nomi, ariel, toss, persil, powder soap, liquid soap, dish soap, dishwashing, jik, bleach, harpic, toilet cleaner, disinfectant, dettol, sunlight powder, fabric softener"],
    ["sponge", "🧽", "Sponges & scourers", "sponge, scrubber, steel wool, scouring pad, vim, scourer, dish sponge"],
    ["broom", "🧹", "Brooms & mops", "broom, mop, sweeping brush, squeegee, duster, dustpan, feather duster, brooms"],
    ["basket", "🧺", "Baskets", "basket, laundry basket, kikapu, baskets"],
    ["bucket", "🪣", "Buckets & basins", "bucket, basin, pail, tub, washing basin, karaayi, buckets"],
    ["toilet-paper", "🧻", "Tissue & toilet paper", "toilet paper, tissue, tissues, toilet roll, serviettes, napkins, paper towel, kitchen towel, wipes, baby wipes, wet wipes, rolls"],
    ["candle", "🕯️", "Candles", "candle, candles, wax"],
    ["matches", "x:matchbox", "Matches", "matches, matchbox, match box, safety matches, kibiriti, match sticks"],
    ["lighter", "🔥", "Lighter", "lighter, fire lighter, firestarter, fire starter"],
    ["charcoal", "x:charcoal", "Charcoal", "charcoal, makaa, sack of charcoal, briquettes, amanda"],
    ["firewood", "🪵", "Firewood & timber", "firewood, wood, timber, log, poles, planks, enku"],
    ["gas", "x:gas-cylinder", "Cooking gas", "gas, cooking gas, lpg, gas cylinder, total gas, shell gas, meko gas, stabex gas, gas refill, hashi gas, oryx gas, cylinder"],
    ["jerrycan", "x:jerrycan", "Jerrycan & paraffin", "jerrycan, jerry can, jerrican, paraffin, kerosene, jerrycans"],
    ["insecticide", "🦟", "Insect control", "insecticide, doom, baygon, raid, mosquito, mosquito coil, coil, repellent, mosquito repellent, fly killer, rungu, mosquito net, net, bed net"],
    ["lightbulb", "💡", "Bulbs & lighting", "bulb, light bulb, energy saver, led bulb, tube light, fluorescent, bulbs, lamp, security light"],
    ["torch", "🔦", "Torch", "torch, flashlight, rechargeable torch, head torch, torches"],
    ["battery", "🔋", "Batteries & power banks", "battery, batteries, dry cells, dry cell, cells, aa, aaa, duracell, tiger head, eveready, power bank, powerbank"],
    ["padlock", "🔒", "Padlocks", "padlock, lock, locks, padlocks"],
    ["key", "🔑", "Keys", "key, keys, key holder, keyholder"],
    ["umbrella", "☂️", "Umbrella", "umbrella, umbrellas"],
    ["bedding", "🛏️", "Bedding", "bed, mattress, bedsheet, bed sheet, bedsheets, blanket, duvet, pillow, pillowcase, bedcover"],
    ["chair", "🪑", "Chairs & furniture", "chair, plastic chair, stool, table, furniture, chairs"],
    ["mirror", "🪞", "Mirror", "mirror, mirrors"],
    ["lantern", "🪔", "Lanterns & tadooba", "tadooba, lantern, hurricane lamp, oil lamp, paraffin lamp, lanterns"],
    ["pest-trap", "🪤", "Rat traps & poison", "mouse trap, rat trap, rat poison, rat killer, mouse poison, traps"],
    ["curtains", "🪟", "Curtains & windows", "curtain, curtains, curtain rod, window, windows, blinds"],
    ["sofa", "🛋️", "Sofas", "sofa, couch, sofa set, settee"],
    ["dustbin", "🗑️", "Dustbins", "dustbin, bin, waste bin, trash can, rubbish bin, dustbins"],
  ],
  personal: [
    ["lotion", "🧴", "Lotion & cream", "lotion, vaseline, petroleum jelly, body lotion, cream, nivea, shea butter, moisturiser, moisturizer, baby oil, glycerine, movit, body oil, sanitizer, hand sanitizer, shampoo, conditioner, shower gel"],
    ["hair", "🪮", "Hair care", "comb, hair comb, afro comb, hair brush, hair food, relaxer, hair oil, braids, weave, wig, extensions, hair extensions, darling, hair pieces, hair dye"],
    ["toothbrush", "🪥", "Toothbrush & toothpaste", "toothbrush, toothpaste, colgate, close up, closeup, aquafresh, sensodyne, whitedent, dental floss, mouthwash, fresh up"],
    ["razor", "🪒", "Razor & shaving", "razor, razor blade, blades, shaving, shaver, gillette, shaving cream, blade"],
    ["makeup", "💄", "Makeup", "lipstick, lip gloss, makeup, make up, cosmetics, powder, face powder, foundation, mascara, eyeliner, lip balm"],
    ["nail-polish", "💅", "Nail care", "nail polish, nail varnish, manicure, cutex, nail, nails polish, nail cutter"],
    ["perfume", "🌸", "Perfume & deodorant", "perfume, body spray, deodorant, roll on, spray, fragrance, cologne, deo"],
    ["pads", "🩸", "Sanitary pads", "sanitary pads, pads, always, kotex, sanitary towels, tampons, pad, secure pads"],
  ],
  baby: [
    ["diapers", "👶", "Diapers & baby care", "diapers, nappies, pampers, huggies, softcare, molfix, baby diapers, nappy, diaper, baby clothes"],
    ["baby-bottle", "🍼", "Baby feeding", "baby bottle, feeding bottle, formula, infant formula, nan, lactogen, baby milk, cerelac, baby food, teat"],
    ["safety-pin", "🧷", "Safety pins", "safety pin, safety pins, pins, nappy pins"],
  ],
  health: [
    ["pills", "💊", "Medicine", "tablets, tablet, panadol, paracetamol, painkiller, medicine, drugs, capsules, antibiotics, amoxyl, amoxicillin, coartem, malaria, dawa, vitamins, supplements, syrup, cough syrup, hedex, ibuprofen, aspirin, piriton, ors, zinc, multivitamin, septrin, deworm, dewormer"],
    ["bandage", "🩹", "First aid", "bandage, plaster, plasters, elastoplast, first aid, gauze, cotton wool, strapping, crepe bandage"],
    ["thermometer", "🌡️", "Thermometer", "thermometer, digital thermometer"],
    ["syringe", "💉", "Syringes", "syringe, syringes, injection, vaccine, needles"],
    ["stethoscope", "🩺", "Medical devices", "stethoscope, bp machine, blood pressure, glucometer, test strips"],
    ["face-mask", "😷", "Face masks", "face mask, mask, masks, surgical mask, nose mask"],
    ["crutches", "🩼", "Crutches & walking aids", "crutches, crutch, walking stick, walking aid"],
  ],
  stationery: [
    ["notebook", "📓", "Exercise books", "exercise book, exercise books, notebook, counter book, counterbook, note book, jotter, book, picfare, graph book, ruled book"],
    ["books", "📚", "Books", "textbook, text book, novel, story book, dictionary, bible, quran, books, reader, revision book"],
    ["pen", "🖊️", "Pens", "pen, pens, biro, bic, ballpoint, ball pen, ball point, gel pen"],
    ["pencil", "✏️", "Pencils", "pencil, pencils, hb pencil, colour pencils, colored pencils, coloured pencils, sharpener, rubber, eraser"],
    ["crayon", "🖍️", "Markers & crayons", "crayon, crayons, marker, markers, highlighter, chalk, permanent marker"],
    ["ruler", "📏", "Rulers", "ruler, rulers, tape measure, measuring tape"],
    ["math-set", "📐", "Mathematical set", "set square, geometry set, maths set, mathematical set, protractor, compass, math set"],
    ["paperclip", "📎", "Clips & staples", "paper clip, paperclips, paper clips, clips, stapler, staples, staple pins"],
    ["pushpin", "📌", "Drawing pins", "drawing pins, push pins, thumb tacks, thumbtacks"],
    ["folder", "📁", "Files & folders", "folder, file, files, box file, document wallet, folders, spring file"],
    ["envelope", "✉️", "Envelopes", "envelope, envelopes, letter, khaki envelope"],
    ["paper", "📄", "Paper", "paper, a4, printing paper, ream, photocopy paper, manila, bond paper, a4 paper, flip chart, ream of paper, photocopying"],
    ["calculator", "🧮", "Calculator", "calculator, abacus, calculators"],
    ["scissors", "✂️", "Scissors", "scissors, scissor, shears, pair of scissors"],
    ["art", "🎨", "Art supplies", "water colour, watercolour, art supplies, drawing, paint set, poster colour, art"],
    ["newspaper", "🗞️", "Newspapers", "newspaper, newspapers, new vision, daily monitor, bukedde, observer, magazine, magazines"],
    ["calendar", "📅", "Calendars & diaries", "calendar, diary, planner, diaries, calendars"],
    ["packaging", "📦", "Packaging & tape", "box, carton, boxes, packaging, tape, sellotape, cello tape, masking tape, glue, super glue, parcel, cartons, gum paste"],
    ["labels", "🏷️", "Labels & price tags", "labels, price tags, price tag, stickers, sticker, tags"],
    ["ledger", "📒", "Cash & receipt books", "cash book, receipt book, invoice book, ledger, delivery book, record book"],
    ["receipt-roll", "🧾", "Till & receipt rolls", "till roll, receipt roll, thermal paper, receipt paper, pos paper, till rolls"],
    ["id-card", "🪪", "ID cards & holders", "id card, card holder, lanyard, badge holder, id holder"],
  ],
  electronics: [
    ["phone", "📱", "Mobile phone", "phone, mobile phone, smartphone, smart phone, cell phone, handset, tecno, itel, infinix, samsung, iphone, nokia, feature phone, oppo, redmi, xiaomi, ipad, tablet phone, phones, spark, phone cover, screen protector"],
    ["laptop", "💻", "Laptop", "laptop, computer, notebook computer, pc, macbook, hp, dell, lenovo, laptops, chromebook"],
    ["desktop", "🖥️", "Desktop & monitor", "desktop, desktop computer, monitor, screen, pc monitor, computer monitor"],
    ["keyboard", "⌨️", "Keyboard", "keyboard, keyboards"],
    ["mouse", "🖱️", "Computer mouse", "mouse, computer mouse, wireless mouse"],
    ["printer", "🖨️", "Printer & ink", "printer, toner, ink, cartridge, photocopier, scanner, printers"],
    ["tv", "📺", "Television", "tv, television, smart tv, flat screen, televisions, led tv"],
    ["decoder", "📡", "Decoder & satellite", "decoder, satellite dish, dish, antenna, aerial, dstv, gotv, startimes, azam, zuku, satellite"],
    ["radio", "📻", "Radio", "radio, radios, fm radio"],
    ["speaker", "🔊", "Speakers", "speaker, speakers, woofer, sound system, home theatre, subwoofer, bluetooth speaker, amplifier"],
    ["headphones", "🎧", "Headphones", "headphones, earphones, headset, earbuds, airpods, ear phones, earpiece"],
    ["camera", "📷", "Camera", "camera, cameras, webcam, cctv, security camera"],
    ["watch", "⌚", "Watch", "watch, wrist watch, smartwatch, smart watch, watches"],
    ["clock", "⏰", "Clock", "clock, alarm clock, wall clock, clocks"],
    ["memory", "💾", "Memory & storage", "memory card, sd card, flash disk, flash drive, flash, usb, pendrive, hard disk, harddisk, external drive, micro sd, memory"],
    ["disc", "💿", "CDs & DVDs", "cd, dvd, disc, movies, music, dvds"],
    ["game", "🎮", "Video games", "game, playstation, ps4, ps5, xbox, console, controller, gamepad, video game, games"],
    ["airtime", "x:airtime", "Airtime & data", "airtime, air time, mtn airtime, airtel airtime, scratch card, data bundle, bundles, top up, recharge, voucher, mtn, airtel, lyca, data, internet bundle"],
    ["sim-card", "📶", "SIM cards", "sim card, sim, simcard, sim cards, line"],
    ["mobile-money", "📲", "Mobile money", "mobile money, momo, mm, money transfer, withdraw, deposit, airtel money, mtn momo"],
    ["charger", "🔌", "Chargers & cables", "extension, extension cable, socket, plug, adaptor, adapter, charger, cable, usb cable, wire, multi plug, extension socket, chargers, charging cable, type c"],
    ["solar", "☀️", "Solar", "solar, solar panel, solar light, solar lamp, sun king, d light, solar home system, inverter"],
    ["microphone", "🎙️", "Microphones", "microphone, mic, microphones, wireless mic"],
  ],
  kitchen: [
    ["plate", "🍽️", "Plates & dinnerware", "plate, plates, dinner set, dishes, crockery, dinnerware, serving dish"],
    ["cutlery", "🍴", "Cutlery", "fork, forks, cutlery, knife and fork, table knife, cutlery set"],
    ["spoon", "🥄", "Spoons", "spoon, spoons, teaspoon, tablespoon, serving spoon, ladle, wooden spoon, mwiko, mingling stick"],
    ["bowl", "🥣", "Bowls", "bowl, bowls, soup bowl, mixing bowl"],
    ["cup", "☕", "Cups & mugs", "cup, cups, mug, mugs, tea cup, teacup"],
    ["glasses", "🥂", "Glasses & tumblers", "glass, wine glass, tumbler, tumblers, drinking glass, glassware"],
    ["pan", "🍳", "Pans & saucepans", "frying pan, pan, saucepan, sufuria, cooking pot, pot, pans, pots, non stick, karai, sauce pan"],
    ["kettle", "🫖", "Kettle & flask", "kettle, teapot, thermos, flask, vacuum flask, jug, electric kettle"],
    ["food-container", "🥡", "Food containers", "takeaway, take away box, food container, lunch box, tupperware, food flask, container, takeaway box"],
    ["knife", "🔪", "Knives & pangas", "knife, knives, kitchen knife, panga, machete, slasher"],
    ["stove", "🔥", "Stoves & cookers", "stove, cooker, gas cooker, charcoal stove, sigiri, jiko, burner, hot plate"],
  ],
  hardware: [
    ["toolbox", "🧰", "Tools", "toolbox, tools, tool box, tool kit"],
    ["hammer", "🔨", "Hammer", "hammer, mallet, hammers"],
    ["screwdriver", "🪛", "Screwdriver", "screwdriver, screw driver, screwdrivers"],
    ["wrench", "🔧", "Spanners & pliers", "spanner, wrench, pliers, spanners"],
    ["saw", "🪚", "Saw", "saw, hacksaw, handsaw"],
    ["nails", "🔩", "Nails & screws", "nails, nail, screws, screw, bolts, washers, nuts and bolts, roofing nails"],
    ["axe", "🪓", "Hoes & axes", "axe, hoe, jembe, pickaxe, forked hoe, axes, hoes"],
    ["ladder", "🪜", "Ladder", "ladder, ladders"],
    ["bricks", "🧱", "Building materials", "bricks, brick, cement, blocks, building materials, sand, aggregate, concrete, tiles, iron sheets, mabaati"],
    ["paint", "🖌️", "Paint & brushes", "paint, paint brush, emulsion, gloss, varnish, sadolin, crown paints, paints, paintbrush"],
    ["rope", "🪢", "Rope", "rope, twine, string, sisal, manila rope, nylon rope"],
    ["chain", "⛓️", "Chains", "chain, chains, bicycle chain"],
    ["magnet", "🧲", "Magnet", "magnet, magnets"],
    ["fuel", "⛽", "Fuel", "petrol, fuel, diesel, gasoline"],
    ["engine-oil", "🛢️", "Engine oil & lubricants", "engine oil, motor oil, oil drum, lubricant, grease, brake fluid, gear oil, lubricants"],
    ["tyre", "🛞", "Tyres", "tyre, tire, tyres, tires, tube, inner tube, wheel"],
    ["bicycle", "🚲", "Bicycle", "bicycle, bike, bicycles, bicycle parts, spokes"],
    ["motorcycle", "🏍️", "Motorcycle & spares", "motorcycle, motorbike, boda, boda boda, motorcycle parts, spare parts, spares, bajaj, tvs"],
    ["helmet", "⛑️", "Helmets", "helmet, hard hat, helmets"],
    ["safety-vest", "🦺", "Safety wear", "reflector, safety vest, reflective jacket, reflector jacket, overalls, overall"],
    ["extinguisher", "🧯", "Fire extinguisher", "fire extinguisher, extinguisher"],
    ["thread", "🧵", "Thread", "thread, sewing thread, cotton reel, threads"],
    ["yarn", "🧶", "Wool & yarn", "wool, yarn, knitting"],
    ["needle", "🪡", "Sewing needle", "sewing needle, needle, needles and thread"],
    ["plumbing", "🚿", "Plumbing", "tap, taps, pipe, pipes, pvc pipe, shower, plumbing, water pipe, elbow, gate valve"],
    ["toilet-fittings", "🚽", "Toilet fittings", "toilet seat, water closet, cistern, toilet fittings, flush"],
    ["door", "🚪", "Doors & hinges", "door, doors, hinges, hinge, door handle, door lock, door frame"],
    ["stones", "🪨", "Stones & gravel", "stones, gravel, hardcore, ballast, murram, stone"],
    ["gear", "⚙️", "Bearings & parts", "gear, bearing, bearings, machine parts, sprocket, gears"],
  ],
  clothing: [
    ["tshirt", "👕", "T-shirts & tops", "t shirt, tshirt, vest, top, polo, jersey, uniform, school uniform, tops, t shirts"],
    ["shirt", "👔", "Shirts & ties", "shirt, shirts, tie, formal shirt, office shirt, ties"],
    ["trousers", "👖", "Trousers & jeans", "trousers, jeans, pants, khaki, trouser"],
    ["shorts", "🩳", "Shorts", "shorts, boxers, sports shorts"],
    ["underwear", "🩲", "Underwear", "underwear, briefs, knickers, panties, boxer"],
    ["swimwear", "👙", "Bras & swimwear", "bra, bras, swimsuit, bikini, swimwear"],
    ["dress", "👗", "Dresses", "dress, dresses, gomesi, skirt, kitenge, busuuti, gown, skirts"],
    ["socks", "🧦", "Socks", "socks, stockings, tights, sock"],
    ["gloves", "🧤", "Gloves", "gloves, glove, mittens"],
    ["scarf", "🧣", "Scarves", "scarf, scarves, shawl, pashmina, leso, kanga"],
    ["coat", "🧥", "Jackets & sweaters", "coat, jacket, sweater, jumper, hoodie, cardigan, blazer, raincoat, jackets, sweaters"],
    ["shoes", "👞", "Shoes & polish", "shoes, shoe, leather shoes, school shoes, shoe polish, kiwi, polish, loafers, kiwi polish"],
    ["sneakers", "👟", "Sneakers", "sneakers, trainers, canvas, rubber shoes, sports shoes, running shoes, snickers shoes"],
    ["heels", "👠", "Heels", "heels, high heels, ladies shoes, stilettos"],
    ["sandals", "👡", "Sandals", "sandals, sandal"],
    ["slippers", "🩴", "Slippers & flip flops", "slippers, flip flops, flipflops, bathroom slippers, open shoes, sapatu, lugabire"],
    ["boots", "🥾", "Boots", "boots, gumboots, gum boots, safety boots"],
    ["cap", "🧢", "Caps", "cap, caps, baseball cap"],
    ["hat", "👒", "Hats", "hat, hats, sun hat, straw hat"],
    ["handbag", "👜", "Handbags", "handbag, hand bag, ladies bag, clutch, handbags"],
    ["backpack", "🎒", "Bags & backpacks", "bag, school bag, backpack, rucksack, bags, laptop bag"],
    ["luggage", "🧳", "Suitcases", "suitcase, luggage, travel bag, trolley bag, suitcases"],
    ["wallet", "👛", "Wallets & purses", "wallet, purse, wallets"],
    ["sunglasses", "🕶️", "Sunglasses", "sunglasses, shades, sun glasses"],
    ["spectacles", "👓", "Spectacles", "spectacles, reading glasses, eye glasses, eyeglasses, glasses frame"],
    ["jewellery", "💍", "Jewellery", "ring, rings, jewellery, jewelry, earrings, necklace, bracelet, ornaments, beads"],
    ["kanzu", "👘", "Kanzu & robes", "kanzu, robe, robes, bathrobe, dressing gown, kanzus"],
    ["ribbon", "🎀", "Ribbons & hair ties", "ribbon, ribbons, hair ribbon, hair tie, bow"],
  ],
  farm: [
    ["seedling", "🌱", "Seeds & seedlings", "seeds, seed, seedlings, maize seed, bean seeds, vegetable seeds, nursery, seedling"],
    ["plant", "🪴", "Plants & flower pots", "potted plant, flower pot, pot plant, plant, plants, flowers pot"],
    ["flowers", "💐", "Flowers", "flowers, bouquet, roses, flower"],
    ["agro-chemicals", "🧪", "Fertiliser & chemicals", "fertilizer, fertiliser, npk, urea, dap, pesticide, herbicide, roundup, acaricide, agro chemicals, fungicide, can fertilizer"],
    ["animal-feed", "🐔", "Poultry & animal feed", "chicken feed, poultry feed, layers mash, chick mash, broiler mash, growers mash, maize bran, bran, animal feed, cattle feed, pig feed, dairy meal, fish feed, live chicken, hen, cock, layers, broilers, chicks, poultry, local chicken"],
    ["goat", "🐐", "Goats & sheep", "live goat, goat, sheep, goats, mbuzi"],
    ["cow", "🐄", "Cattle", "cow, cattle, bull, heifer, calf, cows"],
    ["pet-food", "🐕", "Pet food", "dog food, pet food, cat food, dog, cat, puppy food"],
    ["pig", "🐖", "Pigs", "live pig, pig, pigs, piglet, piglets"],
    ["rabbit", "🐇", "Rabbits", "rabbit, rabbits"],
    ["turkey", "🦃", "Turkeys", "turkey, turkeys, live turkey"],
    ["duck", "🦆", "Ducks", "duck, ducks, live duck"],
    ["sunflower", "🌻", "Sunflower", "sunflower, sunflower seeds, sunflowers"],
  ],
  toys: [
    ["ball", "⚽", "Football", "ball, football, soccer ball, balls"],
    ["basketball", "🏀", "Basketball & netball", "basketball, netball"],
    ["volleyball", "🏐", "Volleyball", "volleyball, volley ball"],
    ["tennis", "🎾", "Tennis", "tennis, tennis ball, racket, racquet"],
    ["teddy", "🧸", "Toys & dolls", "teddy, teddy bear, toy, toys, doll, dolls, soft toy, toy car"],
    ["kite", "🪁", "Kite", "kite, kites"],
    ["yoyo", "🪀", "Yo-yo", "yoyo, yo yo"],
    ["dice", "🎲", "Board games", "dice, ludo, board game, draughts, chess, snakes and ladders"],
    ["cards", "🃏", "Playing cards", "playing cards, cards, deck of cards, matatu"],
    ["puzzle", "🧩", "Puzzles", "puzzle, jigsaw, puzzles"],
    ["balloon", "🎈", "Balloons & party", "balloon, balloons, party, decorations, party pack"],
    ["gift", "🎁", "Gifts", "gift, present, gift wrap, wrapping paper, gifts, hamper"],
    ["party-popper", "🎉", "Party poppers", "party popper, party poppers, confetti, streamers"],
    ["christmas", "🎄", "Christmas decorations", "christmas tree, christmas decorations, xmas tree, tinsel"],
    ["table-tennis", "🏓", "Table tennis", "table tennis, ping pong, ping pong ball"],
    ["badminton", "🏸", "Badminton", "badminton, shuttlecock, shuttlecocks"],
    ["boxing", "🥊", "Boxing gloves", "boxing gloves, boxing, punch bag"],
    ["weights", "🏋️", "Gym weights", "dumbbell, dumbbells, weights, gym, barbell"],
    ["fishing", "🎣", "Fishing gear", "fishing hook, fishing hooks, fishing line, fishing net, hooks, fishing rod"],
    ["guitar", "🎸", "Guitars", "guitar, guitars, adungu"],
    ["drum", "🥁", "Drums", "drum, drums, engoma, drumsticks set"],
  ],
  other: [
    ["shopping-bags", "🛍️", "Shopping bags", "carrier bags, polythene bags, kaveera, kavera, shopping bag, paper bags, gift bag, polythene, carrier bag"],
    ["cigarettes", "🚬", "Cigarettes & tobacco", "cigarette, cigarettes, sportsman, supermatch, embassy, rex, marlboro, tobacco, cigar, shisha, rothmans"],
    ["ticket", "🎟️", "Tickets", "ticket, tickets, raffle, entry ticket"],
    ["prayer", "📿", "Rosaries & beads", "rosary, rosaries, prayer beads, tasbih"],
    ["cash", "💵", "Cash & services", "service, services, charge, fee, fees, commission, labour, delivery"],
  ],
};

/** Twemoji asset name for an emoji: its code points, dropping U+FE0F unless it is a ZWJ sequence. */
export function twemojiFileName(emoji: string): string {
  const points = [...emoji].map((char) => (char.codePointAt(0) ?? 0).toString(16));
  const kept = points.includes("200d") ? points : points.filter((point) => point !== "fe0f");
  return `${kept.join("-")}.svg`;
}

/** File (relative to public/product-images/) that holds a row's picture. */
export function catalogFileName(image: string): string {
  return image.startsWith("x:") ? `x-${image.slice(2)}.svg` : twemojiFileName(image);
}
